server:
  port: 9000

spring:
  application:
    name: studyspace-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # user ??
        - id: user-route
          uri: lb://studyspace-user
          predicates:
              - Path=/api/user/**
        # seat ??
        - id: seat-route
          uri: lb://studyspace-seat
          predicates:
            - Path=/api/seat/**
        # reservation ??
        - id: reservation-route
          uri: lb://studyspace-reservation
          predicates:
          - Path=/api/reservation/**
        # employee ??
        - id: employee-route
          uri: lb://studyspace-employee
          predicates:
            - Path=/api/employee/**
        # product ??
        - id: product-route
          uri: lb://studyspace-product
          predicates:
              - Path=/api/product/**
