server:
  port: 9000

spring:
  application:
    name: studyspace-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # auth ??
        - id: auth-route
          uri: lb://studyspace-auth
          predicates:
            - Path=/api/auth/**